################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/hazard/alocmem.c \
../src/hazard/alocwrk.c \
../src/hazard/cmpmeth.c \
../src/hazard/cntobs.c \
../src/hazard/concrpt.c \
../src/hazard/cput.c \
../src/hazard/cput_d.c \
../src/hazard/cput_dl.c \
../src/hazard/cput_l.c \
../src/hazard/cput_v.c \
../src/hazard/cput_vv.c \
../src/hazard/crpt.c \
../src/hazard/crpt_d.c \
../src/hazard/crpt_dl.c \
../src/hazard/crpt_l.c \
../src/hazard/evntprc.c \
../src/hazard/finprmx.c \
../src/hazard/getconc.c \
../src/hazard/getrisk.c \
../src/hazard/hazard.c \
../src/hazard/hazard_l.c \
../src/hazard/hazard_y.c \
../src/hazard/hazpprc.c \
../src/hazard/hazrd2.c \
../src/hazard/hazrd3.c \
../src/hazard/hazrd4.c \
../src/hazard/hazrerr.c \
../src/hazard/hzrbomb.c \
../src/hazard/hzrg.c \
../src/hazard/hzri.c \
../src/hazard/hzrxmul.c \
../src/hazard/icnsprc.c \
../src/hazard/initprz.c \
../src/hazard/ismuchg.c \
../src/hazard/lcnsprc.c \
../src/hazard/memclc1.c \
../src/hazard/memclc2.c \
../src/hazard/modterm.c \
../src/hazard/obsstat.c \
../src/hazard/opnfils.c \
../src/hazard/outcmod.c \
../src/hazard/outemod.c \
../src/hazard/outeqn.c \
../src/hazard/outequn.c \
../src/hazard/outflag.c \
../src/hazard/outflgs.c \
../src/hazard/outlmod.c \
../src/hazard/outmods.c \
../src/hazard/outparm.c \
../src/hazard/parmprc.c \
../src/hazard/phasidx.c \
../src/hazard/przconc.c \
../src/hazard/rcnsprc.c \
../src/hazard/readc1.c \
../src/hazard/readc2.c \
../src/hazard/readc3.c \
../src/hazard/readct.c \
../src/hazard/readlc.c \
../src/hazard/readobs.c \
../src/hazard/readt.c \
../src/hazard/readwt.c \
../src/hazard/report.c \
../src/hazard/results.c \
../src/hazard/set_restrict.c \
../src/hazard/setconc.c \
../src/hazard/setidxs.c \
../src/hazard/setobs.c \
../src/hazard/setparmno.c \
../src/hazard/setprmf.c \
../src/hazard/setrisk.c \
../src/hazard/setstat.c \
../src/hazard/shape.c \
../src/hazard/stmtprc.c \
../src/hazard/stpwprc.c \
../src/hazard/theta_x.c \
../src/hazard/timeprc.c \
../src/hazard/varnote.c \
../src/hazard/varsrpt.c \
../src/hazard/varterm.c \
../src/hazard/vfynvar.c \
../src/hazard/vput.c \
../src/hazard/vput_d.c \
../src/hazard/vput_dl.c \
../src/hazard/vput_l.c \
../src/hazard/vrpt.c \
../src/hazard/vrpt_d.c \
../src/hazard/vrpt_dl.c \
../src/hazard/vrpt_l.c \
../src/hazard/wghtprc.c \
../src/hazard/writeOutputDatafile.c 

OBJS += \
./src/hazard/alocmem.o \
./src/hazard/alocwrk.o \
./src/hazard/cmpmeth.o \
./src/hazard/cntobs.o \
./src/hazard/concrpt.o \
./src/hazard/cput.o \
./src/hazard/cput_d.o \
./src/hazard/cput_dl.o \
./src/hazard/cput_l.o \
./src/hazard/cput_v.o \
./src/hazard/cput_vv.o \
./src/hazard/crpt.o \
./src/hazard/crpt_d.o \
./src/hazard/crpt_dl.o \
./src/hazard/crpt_l.o \
./src/hazard/evntprc.o \
./src/hazard/finprmx.o \
./src/hazard/getconc.o \
./src/hazard/getrisk.o \
./src/hazard/hazard.o \
./src/hazard/hazard_l.o \
./src/hazard/hazard_y.o \
./src/hazard/hazpprc.o \
./src/hazard/hazrd2.o \
./src/hazard/hazrd3.o \
./src/hazard/hazrd4.o \
./src/hazard/hazrerr.o \
./src/hazard/hzrbomb.o \
./src/hazard/hzrg.o \
./src/hazard/hzri.o \
./src/hazard/hzrxmul.o \
./src/hazard/icnsprc.o \
./src/hazard/initprz.o \
./src/hazard/ismuchg.o \
./src/hazard/lcnsprc.o \
./src/hazard/memclc1.o \
./src/hazard/memclc2.o \
./src/hazard/modterm.o \
./src/hazard/obsstat.o \
./src/hazard/opnfils.o \
./src/hazard/outcmod.o \
./src/hazard/outemod.o \
./src/hazard/outeqn.o \
./src/hazard/outequn.o \
./src/hazard/outflag.o \
./src/hazard/outflgs.o \
./src/hazard/outlmod.o \
./src/hazard/outmods.o \
./src/hazard/outparm.o \
./src/hazard/parmprc.o \
./src/hazard/phasidx.o \
./src/hazard/przconc.o \
./src/hazard/rcnsprc.o \
./src/hazard/readc1.o \
./src/hazard/readc2.o \
./src/hazard/readc3.o \
./src/hazard/readct.o \
./src/hazard/readlc.o \
./src/hazard/readobs.o \
./src/hazard/readt.o \
./src/hazard/readwt.o \
./src/hazard/report.o \
./src/hazard/results.o \
./src/hazard/set_restrict.o \
./src/hazard/setconc.o \
./src/hazard/setidxs.o \
./src/hazard/setobs.o \
./src/hazard/setparmno.o \
./src/hazard/setprmf.o \
./src/hazard/setrisk.o \
./src/hazard/setstat.o \
./src/hazard/shape.o \
./src/hazard/stmtprc.o \
./src/hazard/stpwprc.o \
./src/hazard/theta_x.o \
./src/hazard/timeprc.o \
./src/hazard/varnote.o \
./src/hazard/varsrpt.o \
./src/hazard/varterm.o \
./src/hazard/vfynvar.o \
./src/hazard/vput.o \
./src/hazard/vput_d.o \
./src/hazard/vput_dl.o \
./src/hazard/vput_l.o \
./src/hazard/vrpt.o \
./src/hazard/vrpt_d.o \
./src/hazard/vrpt_dl.o \
./src/hazard/vrpt_l.o \
./src/hazard/wghtprc.o \
./src/hazard/writeOutputDatafile.o 

C_DEPS += \
./src/hazard/alocmem.d \
./src/hazard/alocwrk.d \
./src/hazard/cmpmeth.d \
./src/hazard/cntobs.d \
./src/hazard/concrpt.d \
./src/hazard/cput.d \
./src/hazard/cput_d.d \
./src/hazard/cput_dl.d \
./src/hazard/cput_l.d \
./src/hazard/cput_v.d \
./src/hazard/cput_vv.d \
./src/hazard/crpt.d \
./src/hazard/crpt_d.d \
./src/hazard/crpt_dl.d \
./src/hazard/crpt_l.d \
./src/hazard/evntprc.d \
./src/hazard/finprmx.d \
./src/hazard/getconc.d \
./src/hazard/getrisk.d \
./src/hazard/hazard.d \
./src/hazard/hazard_l.d \
./src/hazard/hazard_y.d \
./src/hazard/hazpprc.d \
./src/hazard/hazrd2.d \
./src/hazard/hazrd3.d \
./src/hazard/hazrd4.d \
./src/hazard/hazrerr.d \
./src/hazard/hzrbomb.d \
./src/hazard/hzrg.d \
./src/hazard/hzri.d \
./src/hazard/hzrxmul.d \
./src/hazard/icnsprc.d \
./src/hazard/initprz.d \
./src/hazard/ismuchg.d \
./src/hazard/lcnsprc.d \
./src/hazard/memclc1.d \
./src/hazard/memclc2.d \
./src/hazard/modterm.d \
./src/hazard/obsstat.d \
./src/hazard/opnfils.d \
./src/hazard/outcmod.d \
./src/hazard/outemod.d \
./src/hazard/outeqn.d \
./src/hazard/outequn.d \
./src/hazard/outflag.d \
./src/hazard/outflgs.d \
./src/hazard/outlmod.d \
./src/hazard/outmods.d \
./src/hazard/outparm.d \
./src/hazard/parmprc.d \
./src/hazard/phasidx.d \
./src/hazard/przconc.d \
./src/hazard/rcnsprc.d \
./src/hazard/readc1.d \
./src/hazard/readc2.d \
./src/hazard/readc3.d \
./src/hazard/readct.d \
./src/hazard/readlc.d \
./src/hazard/readobs.d \
./src/hazard/readt.d \
./src/hazard/readwt.d \
./src/hazard/report.d \
./src/hazard/results.d \
./src/hazard/set_restrict.d \
./src/hazard/setconc.d \
./src/hazard/setidxs.d \
./src/hazard/setobs.d \
./src/hazard/setparmno.d \
./src/hazard/setprmf.d \
./src/hazard/setrisk.d \
./src/hazard/setstat.d \
./src/hazard/shape.d \
./src/hazard/stmtprc.d \
./src/hazard/stpwprc.d \
./src/hazard/theta_x.d \
./src/hazard/timeprc.d \
./src/hazard/varnote.d \
./src/hazard/varsrpt.d \
./src/hazard/varterm.d \
./src/hazard/vfynvar.d \
./src/hazard/vput.d \
./src/hazard/vput_d.d \
./src/hazard/vput_dl.d \
./src/hazard/vput_l.d \
./src/hazard/vrpt.d \
./src/hazard/vrpt_d.d \
./src/hazard/vrpt_dl.d \
./src/hazard/vrpt_l.d \
./src/hazard/wghtprc.d \
./src/hazard/writeOutputDatafile.d 


# Each subdirectory must supply rules for building sources it contributes
src/hazard/%.o: ../src/hazard/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cygwin C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


