#include <string.h>
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
static yyconst short int yy_accept[474] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  120,  118,    1,    1,    6,  117,
        3,  117,  117,    4,    5,  117,  117,  117,  117,  117,
      117,   16,  117,  117,   30,  118,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  116,  117,
      117,  117,  117,  117,   43,  117,  117,  117,  117,   81,
       73,  117,  117,  117,   96,   95,   97,   98,  100,  104,
      106,  102,  111,  112,    1,  117,  117,    4,    4,  117,
        4,  117,  117,  117,  117,   11,  117,  117,  117,  117,

      117,  117,  117,   30,    0,    2,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  116,  117,  117,  117,  117,  117,  117,
       42,  117,  117,  117,  117,   79,  117,  117,   65,  117,
      117,  117,  117,  117,  117,  117,   67,  117,  117,  117,
      117,  117,    4,  117,   18,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,   29,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,   49,  117,
      117,   44,   39,   45,   46,  117,  117,  117,  117,  117,

      117,  117,  117,   85,   83,  117,  117,   69,   71,  117,
      117,  117,  117,  117,  117,  117,    0,  117,    4,  117,
      117,    9,  117,  117,  117,  117,  117,  117,  117,  117,
      117,    7,  117,  117,   29,  117,  117,  117,  117,  117,
      117,  117,   94,  117,  117,  117,  117,  117,  117,  117,
      117,   31,  117,  117,  117,  117,  117,  117,  117,   54,
      117,  117,  117,  117,  117,  117,   82,  117,   75,   77,
       74,  117,  117,   90,  117,   88,  117,  117,  117,  117,
      117,  105,  117,  117,    0,  117,    4,    4,  117,  117,
      117,  117,   20,   15,   14,   27,  117,  117,  117,  117,

      117,   22,  117,  117,  117,   92,   32,  117,  117,  114,
      115,  117,  117,  117,   37,  117,  117,  117,  117,  117,
       48,   40,  117,  117,  117,  117,  117,  117,   53,  117,
      117,   47,   41,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  107,  103,    4,
      117,  117,    8,  117,  117,  117,  117,  117,   10,  117,
      117,  117,  110,  117,  117,  117,  117,  117,  117,  117,
      117,   63,  117,   36,  117,  117,   59,  117,  117,   60,
      117,   56,  117,  117,  117,  117,  117,  117,  117,  117,
       87,  117,  117,   72,  117,  117,  117,  117,  117,   12,

      117,   28,   26,   25,   17,  117,  117,  117,  117,   34,
       35,  117,  117,   33,  117,  117,  117,  117,  117,   61,
      117,   55,  117,   50,  117,   66,  117,   78,  117,  117,
      117,   70,  117,   99,  101,  117,   19,  117,  117,   24,
       93,  117,  113,  117,  108,  117,   62,   58,   51,   57,
       52,   80,   76,   86,   84,  117,  117,   68,   13,  117,
      117,  109,  117,   64,  117,  117,   21,  117,   38,   91,
       89,   23,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        2,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       11,   11,   11,   11,   11,   11,   11,    1,   14,   15,
       16,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
        1,    1,    1,    1,   44,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    1,
        2,    2,    2,    1,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2
    } ;

static yyconst short int yy_base[483] =
    {   0,
        0,   17,   27,    0,   63,   80,   93,    0,  133,  150,
      642,  641,  160,    0,  183,    0,  217,  227,  237,    0,
        0,   17,   27,   34,  656,  659,   43,   51,  659,    0,
      659,   90,   93,   98,  659,  623,  636,  635,   82,   18,
      614,  616,  612,  612,  108,  634,  609,  614,  157,  625,
      612,  103,  624,  624,  157,  148,  615,  618,  123,  610,
      616,  600,  610,  617,  596,  595,   37,  610,  168,  171,
      156,  599,  598,  224,  659,  659,  659,  588,  597,  595,
      591,  588,  659,  659,  190,    0,  204,  236,  263,  239,
      268,  593,  586,  579,  580,    0,  258,  590,  582,   92,

      600,  595,  284,  186,  602,  659,  584,  583,  578,  590,
      591,  588,  590,  571,  585,  570,  570,  582,  567,  573,
      579,  570,  573,  201,  565,  568,  578,  554,  564,  278,
        0,  555,  574,  565,  570,    0,  553,  553,    0,  546,
      547,  221,  566,  554,  248,  561,    0,  562,  561,  541,
      558,  560,  290,  298,  250,  559,  558,  549,  542,  541,
      540,  536,  548,  544,  537,  547,  530,  543,  213,  543,
      527,  533,  530,  531,  528,  532,  535,  525,  535,  169,
      523,  516,  530,  518,  528,  525,  523,  510,    0,  295,
      516,    0,    0,    0,    0,  516,  525,  515,  505,  501,

      226,  518,  504,    0,  268,  500,  511,  505,  498,  501,
      504,  503,  509,  508,  494,  316,  322,  325,  328,  502,
      505,    0,  491,  488,  311,  500,  486,  496,  486,  502,
      482,    0,  492,  484,  223,  487,  478,  472,  476,  474,
      475,  273,    0,  474,  477,  478,  471,  470,  470,  484,
      463,    0,  477,  483,  482,  470,  476,  460,   19,  465,
      457,  265,  476,  470,  454,  451,    0,  472,  452,  470,
        0,  461,  464,    0,  449,  449,  446,  464,  441,  442,
      441,    0,  443,  440,  332,  336,  340,  343,  439,  440,
      453,  451,  436,    0,    0,    0,  449,  439,  443,  425,

      441,  435,  443,  442,  445,    0,    0,  426,  429,    0,
        0,  428,  421,  436,    0,  425,  430,  418,  428,  416,
        0,    0,  419,  422,  432,  236,  436,  410,    0,  409,
      428,    0,    0,  416,  426,  408,  420,  406,  409,  406,
      401,  405,  401,  393,  408,  412,  411,    0,    0,  346,
      405,  391,    0,  394,  406,  391,  389,  405,    0,  387,
      401,  386,    0,  390,  394,  384,  383,  386,  379,  380,
      394,  387,  376,    0,  386,  373,    0,  396,  378,    0,
      395,    0,  377,  376,  369,  382,  369,  365,  363,  359,
        0,  379,  355,    0,  360,  373,  372,  361,  370,    0,

      356,    0,    0,    0,    0,  350,  352,  351,  348,    0,
        0,  349,  363,    0,  347,  351,  360,  363,  362,    0,
      361,    0,  355,    0,  356,    0,  340,    0,  284,  349,
      336,    0,  351,    0,    0,  341,    0,  332,  333,    0,
        0,  347,    0,  333,    0,  300,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  294,  287,    0,    0,  299,
      283,    0,  263,    0,  266,  245,    0,  211,    0,    0,
        0,    0,  659,  359,  361,  363,  239,  210,  365,  178,
      125,  112
    } ;

static yyconst short int yy_def[483] =
    {   0,
      474,  474,    2,    3,  475,  475,    2,    7,  476,  476,
       10,   10,    2,   13,   13,   15,   10,   10,   15,   19,
       10,   10,   10,   10,  473,  473,  473,  473,  473,  477,
      473,  477,  477,  477,  473,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  478,  479,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  480,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  473,  473,  473,  477,  477,  477,
      477,  477,  473,  473,  473,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,

      477,  477,  481,  478,  479,  473,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  480,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  482,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,

      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  473,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  482,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  473,  477,  477,  473,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,

      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  473,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,

      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,    0,  473,  473,  473,  473,  473,  473,  473,
      473,  473
    } ;

static yyconst short int yy_nxt[704] =
    {   0,
       26,   27,   28,   29,   26,   26,   26,   32,   33,   26,
       34,   34,   34,   31,   26,   26,   26,   26,   27,   28,
       29,   26,   26,   26,   32,   33,   26,   34,   34,   34,
       31,   26,   26,   26,   32,   33,  326,   34,   34,   34,
      327,   83,   35,   84,   85,   85,   36,   37,   83,   97,
       84,   38,   85,   85,  132,   98,   39,   40,   41,   42,
       43,  133,   44,   26,   27,   28,   29,   26,   26,   26,
       30,   30,   26,   30,   30,   30,   31,   26,   35,   26,
       26,   27,   28,   29,   26,   26,   26,   30,   30,   26,
       30,   30,   30,   31,   26,   35,   26,   46,   87,   95,

       88,   88,   88,   89,   89,   89,   90,   96,   91,   91,
       91,   47,   48,  235,   49,   86,  103,  165,   50,   51,
      114,   52,  115,  166,   53,   54,  169,   55,   56,   57,
       86,   86,   58,   26,   27,   28,   29,   26,   26,   26,
       30,   30,   26,   30,   30,   30,   31,   26,   26,   26,
       26,   27,   28,   29,   26,   26,   26,   30,   30,   26,
       30,   30,   30,   31,   26,   26,   26,   32,   33,  120,
       34,   34,   34,  140,  109,   35,  118,   60,  119,  124,
       61,   62,   63,   64,  121,  135,  246,  141,  137,   65,
       66,   85,   85,   86,  103,  110,   67,  111,  247,   68,

       30,   69,  138,   30,   30,   70,   30,  136,   86,   86,
      139,  104,   71,   72,  153,  153,  153,   73,   74,   30,
       86,   86,   30,   75,   32,   33,   76,   34,   34,   34,
       86,   86,   35,   75,   32,   33,   76,   34,   34,   34,
       86,  472,   35,   77,   87,  144,   88,   88,   88,   89,
       89,   89,  145,  203,  204,   30,  205,  378,   78,   30,
      146,  269,   79,  147,  270,  379,   80,   30,   81,  208,
      220,   30,   82,   89,   89,   89,   90,  159,   91,   91,
       91,  471,  330,  209,  154,  221,  160,  470,  161,  331,
      162,   86,   86,  310,   86,   86,   86,  192,  469,  193,

      153,  153,  153,  217,  273,  218,  194,  274,  219,  219,
      219,  216,  256,  311,  468,  257,  258,  454,  259,  455,
      467,  285,  466,  286,  260,  261,  287,  287,  287,  465,
      464,  262,  288,  288,  288,  219,  219,  219,  219,  219,
      219,  293,  350,  350,  350,  294,  287,  287,  287,  295,
      287,  287,  287,  288,  288,  288,  350,  350,  350,   30,
       30,   45,   45,   59,   59,  105,  105,  463,  462,  461,
      460,  459,  458,  457,  456,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,

      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  329,  328,  325,  324,  323,  322,

      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  292,  291,  290,  289,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  272,  271,
      268,  267,  266,  265,  264,  263,  255,  254,  253,  252,
      251,  250,  249,  248,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  215,  214,  213,
      212,  211,  210,  207,  206,  202,  201,  200,  199,  198,
      197,  196,  195,  191,  190,  189,  188,  187,  186,  185,

      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  106,  168,  167,  164,  163,
      158,  157,  156,  155,  152,  151,  150,  149,  148,  143,
      142,  134,  131,  130,  129,  128,  127,  126,  125,  123,
      122,  117,  116,  113,  112,  108,  107,  106,  102,  101,
      100,   99,   94,   93,   92,  473,   35,   35,   25,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,

      473,  473,  473
    } ;

static yyconst short int yy_chk[704] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,   21,   21,    1,
       21,   21,   21,    1,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    2,   22,   22,    2,   22,   22,   22,
        2,    2,    2,    2,    3,    3,  259,    3,    3,    3,
      259,   23,    3,   23,   27,   27,    3,    3,   24,   40,
       24,    3,   28,   28,   67,   40,    3,    3,    3,    3,
        3,   67,    3,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    7,   32,   39,

       32,   32,   32,   33,   33,   33,   34,   39,   34,   34,
       34,    7,    7,  482,    7,   45,   45,  100,    7,    7,
       52,    7,   52,  100,    7,    7,  481,    7,    7,    7,
       59,   59,    7,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   13,   13,   56,
       13,   13,   13,   71,   49,   13,   55,   13,   55,  480,
       13,   13,   13,   13,   56,   69,  180,   71,   70,   13,
       13,   85,   85,  104,  104,   49,   13,   49,  180,   13,

       15,   15,   70,   15,   15,   15,   15,   69,  124,  124,
       70,  478,   15,   15,   87,   87,   87,   15,   15,   15,
      169,  169,   15,   17,   17,   17,   17,   17,   17,   17,
      235,  235,   17,   18,   18,   18,   18,   18,   18,   18,
      477,  468,   18,   19,   88,   74,   88,   88,   88,   90,
       90,   90,   74,  142,  142,   19,  142,  326,   19,   19,
       74,  201,   19,   74,  201,  326,   19,   19,   19,  145,
      155,   19,   19,   89,   89,   89,   91,   97,   91,   91,
       91,  466,  262,  145,   89,  155,   97,  465,   97,  262,
       97,  103,  103,  242,  103,  103,  103,  130,  463,  130,

      153,  153,  153,  154,  205,  154,  130,  205,  154,  154,
      154,  153,  190,  242,  461,  190,  190,  429,  190,  429,
      460,  216,  457,  216,  190,  190,  216,  216,  216,  456,
      446,  190,  217,  217,  217,  218,  218,  218,  219,  219,
      219,  225,  285,  285,  285,  225,  286,  286,  286,  225,
      287,  287,  287,  288,  288,  288,  350,  350,  350,  474,
      474,  475,  475,  476,  476,  479,  479,  444,  442,  439,
      438,  436,  433,  431,  430,  427,  425,  423,  421,  419,
      418,  417,  416,  415,  413,  412,  409,  408,  407,  406,
      401,  399,  398,  397,  396,  395,  393,  392,  390,  389,

      388,  387,  386,  385,  384,  383,  381,  379,  378,  376,
      375,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  362,  361,  360,  358,  357,  356,  355,  354,  352,
      351,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  331,  330,  328,  327,  325,
      324,  323,  320,  319,  318,  317,  316,  314,  313,  312,
      309,  308,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  293,  292,  291,  290,  289,  284,  283,  281,  280,
      279,  278,  277,  276,  275,  273,  272,  270,  269,  268,
      266,  265,  264,  263,  261,  260,  258,  257,  256,  255,

      254,  253,  251,  250,  249,  248,  247,  246,  245,  244,
      241,  240,  239,  238,  237,  236,  234,  233,  231,  230,
      229,  228,  227,  226,  224,  223,  221,  220,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  203,  202,
      200,  199,  198,  197,  196,  191,  188,  187,  186,  185,
      184,  183,  182,  181,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  156,  152,  151,  150,
      149,  148,  146,  144,  143,  141,  140,  138,  137,  135,
      134,  133,  132,  129,  128,  127,  126,  125,  123,  122,

      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  105,  102,  101,   99,   98,
       95,   94,   93,   92,   82,   81,   80,   79,   78,   73,
       72,   68,   66,   65,   64,   63,   62,   61,   60,   58,
       57,   54,   53,   51,   50,   48,   47,   46,   44,   43,
       42,   41,   38,   37,   36,   25,   12,   11,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,

      473,  473,  473
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "hazard_l.l"
#define INITIAL 0
#line 4 "hazard_l.l"
/*
  (12/21/96) RAM
         Changed hazard.l RESTRICT production added yylval.nam = yytext
         RESTRICT command had stopped working somtime mid 1995
         This change is made pending testing under PC version of gnu yacc/flex.
*/
#include <stdio.h>
#include "hazard_y.h" /* parser defines */
int yylnctr,yysynerr;
/* Regular expressions */
/* ------------------- */
/* start conditions make things more complicated */
#define HZRP 1
#define DSNM 2
#define STMT 3
#define VARS 4
#define ICNS 5
#define PARM 6
#define STEP 7
#define PHVR 8
#define PHOP 9
#define CTRL 10
#define BNDL 11

#line 30 "hazard_l.l"
#undef YYLMAX
#define YYLMAX 4096
#line 704 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 33 "hazard_l.l"


#line 858 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 474 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 659 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "hazard_l.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "hazard_l.l"
yylnctr++;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "hazard_l.l"
{ BEGIN STMT; yylnctr++; return ';'; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 38 "hazard_l.l"
{ sscanf(yytext,"%lf",&yylval.real);
                                          return NUMBER; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "hazard_l.l"
return '=';
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "hazard_l.l"
{ BEGIN HZRP; yysynerr = 0; yylnctr = 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "hazard_l.l"
return PROC;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "hazard_l.l"
{ yylval.name = yytext; return HAZARD; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "hazard_l.l"
{ BEGIN DSNM; return DATA; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "hazard_l.l"
{ BEGIN DSNM; return OUTHAZ; }
	YY_BREAK
case 11:
#line 47 "hazard_l.l"
case 12:
YY_RULE_SETUP
#line 47 "hazard_l.l"
return MAXITER;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "hazard_l.l"
return CONDITION;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "hazard_l.l"
return NOCOV;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "hazard_l.l"
return NOCOR;
	YY_BREAK
case 16:
#line 52 "hazard_l.l"
case 17:
YY_RULE_SETUP
#line 52 "hazard_l.l"
return PRINTIT;
	YY_BREAK
case 18:
#line 54 "hazard_l.l"
case 19:
YY_RULE_SETUP
#line 54 "hazard_l.l"
return CONSERVE;
	YY_BREAK
case 20:
#line 56 "hazard_l.l"
case 21:
YY_RULE_SETUP
#line 56 "hazard_l.l"
return NOCONSERVE;
	YY_BREAK
case 22:
#line 58 "hazard_l.l"
case 23:
YY_RULE_SETUP
#line 58 "hazard_l.l"
return QUASINEWTON;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "hazard_l.l"
return STEEPEST;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "hazard_l.l"
return NUMERIC;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "hazard_l.l"
return NOPRINT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "hazard_l.l"
return NOLOG;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "hazard_l.l"
return NONOTES;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "hazard_l.l"
{ BEGIN HZRP; return LIBMEM; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "hazard_l.l"
{ BEGIN HZRP; yylval.name = yytext; return NAME;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 66 "hazard_l.l"
{ BEGIN VARS; return TIME; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 67 "hazard_l.l"
{ BEGIN VARS; return EVENT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "hazard_l.l"
{ BEGIN VARS; return RCENSOR; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "hazard_l.l"
{ BEGIN ICNS; return ICENSOR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "hazard_l.l"
{ BEGIN VARS; return LCENSOR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "hazard_l.l"
{ BEGIN VARS; return WEIGHT; }
	YY_BREAK
case 37:
#line 73 "hazard_l.l"
case 38:
YY_RULE_SETUP
#line 73 "hazard_l.l"
{ BEGIN PARM; return PARAMETERS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "hazard_l.l"
return MUE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "hazard_l.l"
return DELTA;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "hazard_l.l"
return THALF;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 77 "hazard_l.l"
return NU;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "hazard_l.l"
return M;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 79 "hazard_l.l"
return MUC;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 80 "hazard_l.l"
return MUL;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 81 "hazard_l.l"
return TAU;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 82 "hazard_l.l"
return GAMMA;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 83 "hazard_l.l"
return ALPHA;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 84 "hazard_l.l"
return ETA;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 85 "hazard_l.l"
return WEIBULL;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 86 "hazard_l.l"
return FIXDELTA;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 87 "hazard_l.l"
return FIXTHALF;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 88 "hazard_l.l"
return FIXNU;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 89 "hazard_l.l"
return FIXM;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 90 "hazard_l.l"
return FIXMNU1;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 91 "hazard_l.l"
return FIXTAU;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 92 "hazard_l.l"
return FIXGAMMA;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 93 "hazard_l.l"
return FIXALPHA;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 94 "hazard_l.l"
return FIXETA;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 95 "hazard_l.l"
return FIXGE2;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 96 "hazard_l.l"
return FIXGAE2;
	YY_BREAK
case 62:
#line 98 "hazard_l.l"
case 63:
#line 99 "hazard_l.l"
case 64:
YY_RULE_SETUP
#line 99 "hazard_l.l"
{ BEGIN STEP; return STEPWISE; }
	YY_BREAK
case 65:
#line 101 "hazard_l.l"
case 66:
#line 102 "hazard_l.l"
case 67:
#line 103 "hazard_l.l"
case 68:
YY_RULE_SETUP
#line 103 "hazard_l.l"
return STEPWISE;
	YY_BREAK
case 69:
#line 105 "hazard_l.l"
case 70:
YY_RULE_SETUP
#line 105 "hazard_l.l"
return SLENTRY;
	YY_BREAK
case 71:
#line 107 "hazard_l.l"
case 72:
YY_RULE_SETUP
#line 107 "hazard_l.l"
return SLSTAY;
	YY_BREAK
case 73:
#line 109 "hazard_l.l"
case 74:
YY_RULE_SETUP
#line 109 "hazard_l.l"
return MOVE;
	YY_BREAK
case 75:
#line 111 "hazard_l.l"
case 76:
YY_RULE_SETUP
#line 111 "hazard_l.l"
return MAXSTEPS;
	YY_BREAK
case 77:
#line 113 "hazard_l.l"
case 78:
YY_RULE_SETUP
#line 113 "hazard_l.l"
return MAXVARS;
	YY_BREAK
case 79:
#line 115 "hazard_l.l"
case 80:
YY_RULE_SETUP
#line 115 "hazard_l.l"
return BACKWARD;
	YY_BREAK
case 81:
#line 117 "hazard_l.l"
case 82:
YY_RULE_SETUP
#line 117 "hazard_l.l"
return FAST;
	YY_BREAK
case 83:
#line 119 "hazard_l.l"
case 84:
YY_RULE_SETUP
#line 119 "hazard_l.l"
return NOPRINTS;
	YY_BREAK
case 85:
#line 121 "hazard_l.l"
case 86:
YY_RULE_SETUP
#line 121 "hazard_l.l"
return NOPRINTQ;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 122 "hazard_l.l"
return ROBUST;
	YY_BREAK
case 88:
#line 124 "hazard_l.l"
case 89:
YY_RULE_SETUP
#line 124 "hazard_l.l"
return SEMIROBUST;
	YY_BREAK
case 90:
#line 126 "hazard_l.l"
case 91:
YY_RULE_SETUP
#line 126 "hazard_l.l"
return ONEWAY;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 127 "hazard_l.l"
{ BEGIN PHVR; 
                          yylval.name = yytext; 
                          return EARLY; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 130 "hazard_l.l"
{ BEGIN PHVR; 
                          yylval.name = yytext;
                          return CONSTANT; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 133 "hazard_l.l"
{ BEGIN PHVR; 
                          yylval.name = yytext; 
                          return LATE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 136 "hazard_l.l"
{ BEGIN PHOP; return '/'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 137 "hazard_l.l"
return ',';
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 138 "hazard_l.l"
{ BEGIN PHVR; return ','; }
	YY_BREAK
case 98:
#line 140 "hazard_l.l"
case 99:
YY_RULE_SETUP
#line 140 "hazard_l.l"
return EXCLUDE;
	YY_BREAK
case 100:
#line 142 "hazard_l.l"
case 101:
YY_RULE_SETUP
#line 142 "hazard_l.l"
return INCLUDE;
	YY_BREAK
case 102:
#line 144 "hazard_l.l"
case 103:
YY_RULE_SETUP
#line 144 "hazard_l.l"
return START;
	YY_BREAK
case 104:
#line 146 "hazard_l.l"
case 105:
YY_RULE_SETUP
#line 146 "hazard_l.l"
return MOVE;
	YY_BREAK
case 106:
#line 148 "hazard_l.l"
case 107:
YY_RULE_SETUP
#line 148 "hazard_l.l"
return ORDER;
	YY_BREAK
case 108:
#line 150 "hazard_l.l"
case 109:
YY_RULE_SETUP
#line 150 "hazard_l.l"
{ BEGIN VARS;
                          yylval.name = yytext;
                          return RESTRICT; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 153 "hazard_l.l"
{ BEGIN BNDL; return BUNDLE; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 154 "hazard_l.l"
return '<';
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 155 "hazard_l.l"
{ BEGIN VARS; return '>'; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 156 "hazard_l.l"
{ BEGIN CTRL; return OBSCOUNT; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 157 "hazard_l.l"
{ BEGIN CTRL; return JOBID; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 158 "hazard_l.l"
{ BEGIN CTRL; return JOBIX; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 159 "hazard_l.l"
{ yylval.name = yytext;
                                          return NAME; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 161 "hazard_l.l"
{ printf("$ERROR: Unexpected text, stmt %d: %s\n",yylnctr,yytext);
                                  yysynerr = 1; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 163 "hazard_l.l"
{ printf("$ERROR: Unexpected char, stmt %d: %s\n",yylnctr,yytext);
                  yysynerr = 1; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 165 "hazard_l.l"
ECHO;
	YY_BREAK
#line 1464 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(HZRP):
case YY_STATE_EOF(DSNM):
case YY_STATE_EOF(STMT):
case YY_STATE_EOF(VARS):
case YY_STATE_EOF(ICNS):
case YY_STATE_EOF(PARM):
case YY_STATE_EOF(STEP):
case YY_STATE_EOF(PHVR):
case YY_STATE_EOF(PHOP):
case YY_STATE_EOF(CTRL):
case YY_STATE_EOF(BNDL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 474 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 474 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 473);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters inter than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 165 "hazard_l.l"

