#include <stdio.h>
#include <string.h>

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

/* Initilize the run */
#include "hazard.h"
#include <stmtopts.h>
#include <xlmode.h>
#include <hzf_log1.h>
#include <hzfxit.h>
#include <hzd_log.h>

#include <yyparse.h>
#include <stdlib.h>
#include <string.h>

/****************************************************************/

void initprz(void){

  /**
     VERSION is defined in the config.h file generated by the
     configure script.
  */

  char version_text[128];
  snprintf(version_text, sizeof(version_text),
	   "Note: Procedure HAZARD (C-Version %s)", VERSION);

  /*
    yyparse parses the input command file (.sas) supplied to the 
    stdin at program execution. 
  */
  
  HZD_LOG_DEBUG("Parse input instructions");

  yyparse();

  HZD_LOG_DEBUG("Checking for parse errors");

  stmtptr = anchor;
  C->errorno = 0;
  if(!yysynerr) {
    /*  I would realy like to enum these stmtopts parameters to 
	make them human legible.  */
    if(stmtopts(40))
      xlmode(0);
    if(stmtopts(41))
      xlmode(1);
  }


  HZD_LOG_DEBUG("Dump run headers");
  /* Dump a run header */
  hzf_log1(" ");

  hzf_log1(version_text);
#ifdef HAZOPTIM
  hzf_log1("      Optimized version");
#endif
#ifdef HZD_DEBUG_BUILD
  hzf_log1("      DEBUGGING VERSION");
#endif
  hzf_log1("      The Cleveland Clinic Foundation");
  hzf_log1("      9500 Euclid Avenue");
  hzf_log1("      Cleveland, Ohio 44195");
  hzf_log1("      Phone: (216) 444-6712");
  hzf_log1("      Email: hazard@bio.ri.ccf.org");
  
  /* For errors parsing the input command file, stop here 
     with a message */
  if(yysynerr) {
    hzf_log1("Note: PROCEDURE TERMINATING DUE TO ABOVE ERRORS.");
    hzfxit("SYNTAX");
  }
}
